# Blinded corpus: datasets that all show the pluralistic-ignorance pattern,
# generated by either mechanism, delivered as anonymous files plus a key.
#
#   generate_blinded_corpus(settings, out_dir, progress)  ->  key data frame
#   score_predictions(key, predictions)                   ->  list of metrics
#
# CLI:  Rscript R/corpus.R <out_dir> [--per N] [--respondents M] [--seed S]
#
# Output layout:
#   <out_dir>/blinded/README.txt                     what the statisticians get
#   <out_dir>/blinded/datasets/dataset_0001/respondents.csv [ego_network.csv]
#   <out_dir>/key.csv                                dataset_id -> mechanism, parameters, ground truth
#   <out_dir>/key_details/dataset_0001/state.rds     full fixed point (optional)
#   <out_dir>/corpus.json                            the settings used

MECHANISM <- c(S1 = "genuine pluralistic ignorance", S3 = "genuine pluralistic ignorance", S2 = "friendship paradox")

default_corpus_settings <- function() {
  list(
    per_scenario = c(S1 = 30L, S3 = 30L, S2 = 30L),   # datasets per scenario
    respondents = 150L,                                 # per dataset (capped at n)
    records = c("degree", "declaration", "ego_perceptions", "neighbor_degrees"),
    n_range = c(200L, 500L),
    ba_m = c(1L, 2L, 3L),                               # links per new agent, drawn uniformly
    prevalence_range = c(0.55, 0.85),                   # pi0 (S1, S2) and psi (S3)
    conformity_a_range = list(S1 = c(3, 8), S3 = c(2, 6)),   # c ~ beta(a, 1)
    lambda_range = c(2, 8),
    centrality = c("degree", "eigenvector", "betweenness"),
    max_attempt_factor = 30L,                           # give up on a scenario after this many attempts per accepted dataset
    write_state = TRUE,
    seed = 1L
  )
}

pick <- function(x) x[sample.int(length(x), 1L)]        # safe for length-1 vectors (sample(x, 1) is not)

draw_dataset_params <- function(sc, s, attempt) {
  sc_i <- match(sc, c("S1", "S2", "S3"))
  set.seed(as.integer((s$seed * 1000003 + sc_i * 7919 + attempt) %% 2147483647))
  p <- list(scenario = sc, topology = "ba", n = pick(seq(s$n_range[1], s$n_range[2])), m = pick(s$ba_m))
  prev <- runif(1, s$prevalence_range[1], s$prevalence_range[2])
  if (sc == "S1") { p$pi0 <- prev; p$c_dist <- "beta"; p$c_a <- runif(1, s$conformity_a_range$S1[1], s$conformity_a_range$S1[2]); p$c_b <- 1 }
  if (sc == "S3") { p$psi <- prev; p$c_dist <- "beta"; p$c_a <- runif(1, s$conformity_a_range$S3[1], s$conformity_a_range$S3[2]); p$c_b <- 1 }
  if (sc == "S2") { p$pi0 <- prev; p$pure <- TRUE; p$lambda <- runif(1, s$lambda_range[1], s$lambda_range[2]); p$centrality <- pick(s$centrality) }
  # run seed; the survey and blinding draw from separate seeds (offsets far apart so streams never coincide)
  p$seed <- as.integer((s$seed * 100000 + sc_i * 10000 + attempt) %% 2147483647)
  p
}

# Recode attitudes 0 <-> 1 consistently across all columns of a survey.
flip_coding <- function(sv) {
  r <- sv$respondents; r$attitude <- 1L - r$attitude; r$declaration <- 1L - r$declaration; r$perceived_prevalence <- 1 - r$perceived_prevalence
  sv$respondents <- r
  if (!is.null(sv$ego_network)) { e <- sv$ego_network; e$perceived_neighbor_attitude <- 1L - e$perceived_neighbor_attitude; e$neighbor_attitude <- 1L - e$neighbor_attitude; sv$ego_network <- e }
  sv
}

# Anonymous identifiers: respondents are numbered 1..m in random order; any
# other node that appears as a contact (linked design only) gets a number above
# m, also in random order. Nothing about the population size leaks.
anonymize_ids <- function(sv, n) {
  egos <- sv$respondents$respondent_id; m <- length(egos)
  ids <- integer(n)
  ids[egos] <- sample.int(m)
  others <- setdiff(seq_len(n), egos)
  if (length(others)) ids[others] <- m + sample.int(length(others))
  sv$respondents$respondent_id <- ids[sv$respondents$respondent_id]
  sv$respondents <- sv$respondents[order(sv$respondents$respondent_id), ]
  if (!is.null(sv$ego_network)) {
    sv$ego_network$respondent_id <- ids[sv$ego_network$respondent_id]
    sv$ego_network$neighbor_id <- ids[sv$ego_network$neighbor_id]
    sv$ego_network <- sv$ego_network[order(sv$ego_network$respondent_id, sv$ego_network$neighbor_slot), ]
  }
  rownames(sv$respondents) <- NULL; rownames(sv$ego_network) <- NULL
  sv
}

# Does the sample itself show the pattern? (majority attitude among respondents,
# and its holders' mean perceived share of it below 1/2). Coding-invariant.
sample_shows_pattern <- function(resp) {
  p <- mean(resp$attitude); maj <- if (p >= 0.5) 1L else 0L
  own <- if (maj == 1L) resp$perceived_prevalence else 1 - resp$perceived_prevalence
  mean(own[resp$attitude == maj], na.rm = TRUE) < 0.5
}

blinded_readme <- function(records, n_datasets) {
  cols <- c("respondent_id: anonymous identifier of the respondent (1 to the number of respondents, in no meaningful order)",
            "attitude: the respondent's own privately reported attitude (0 or 1)",
            "perceived_prevalence: the respondent's estimate of the share of the population holding attitude 1")
  if ("degree" %in% records) cols <- c(cols, "degree: the respondent's number of social contacts")
  if ("declaration" %in% records) cols <- c(cols, "declaration: the attitude the respondent expresses publicly (0 or 1)")
  ego <- NULL
  if ("ego_perceptions" %in% records) {
    ego <- c("respondent_id: the respondent reporting", "neighbor_slot: the position of the contact in the respondent's report (1, 2, ...); contacts are anonymous and listed in random order",
             "perceived_neighbor_attitude: the attitude the respondent believes this contact holds (0 or 1)")
    if ("neighbor_degrees" %in% records) ego <- c(ego, "neighbor_degree: this contact's number of social contacts, as reported")
    if ("linked" %in% records) ego <- c(ego, "neighbor_id: the contact's anonymous identifier (matches respondent_id when the contact is also a respondent)", "neighbor_attitude: the contact's own privately reported attitude")
  }
  paste0(
    "BLINDED SURVEY DATASETS\n\n",
    sprintf("This folder holds %d datasets. Each is a survey of a random sample of respondents from one population of people connected by a social network. ", n_datasets),
    "In every population, most people hold one attitude toward a proposition, yet the people holding that majority attitude believe, on average, that it is held by a minority.\n\n",
    "Two different processes can produce this pattern:\n",
    "  (A) Genuine pluralistic ignorance: people's perceptions of their contacts' attitudes are systematically wrong, because contacts publicly express an attitude that differs from the one they privately hold.\n",
    "  (B) Network structure: every person perceives their contacts' attitudes accurately, but well-connected people are over-represented in everyone's circle of contacts, and the well-connected disproportionately hold the minority attitude.\n\n",
    "Each dataset was produced by exactly one of these processes. The task is to decide, for each dataset, which one, and to say how confident you are.\n\n",
    "Attitudes are coded 0 and 1; the coding is arbitrary and differs between datasets. Populations, sample sizes and other details vary between datasets.\n\n",
    "FILES\n\n",
    "datasets/dataset_XXXX/respondents.csv, one row per respondent:\n", paste0("  - ", cols, collapse = "\n"), "\n",
    if (!is.null(ego)) paste0("\ndatasets/dataset_XXXX/ego_network.csv, one row per (respondent, contact) pair, for the contacts each respondent reported on:\n", paste0("  - ", ego, collapse = "\n"), "\n") else "",
    "\nPREDICTIONS\n\nReturn a CSV with the columns dataset_id, prediction (\"genuine\" or \"structure\"), and optionally score (your probability that the dataset is genuine pluralistic ignorance).\n")
}

generate_blinded_corpus <- function(settings = default_corpus_settings(), out_dir, progress = NULL) {
  s <- modifyList(default_corpus_settings(), settings)
  dir.create(file.path(out_dir, "blinded", "datasets"), recursive = TRUE, showWarnings = FALSE)
  if (s$write_state) dir.create(file.path(out_dir, "key_details"), recursive = TRUE, showWarnings = FALSE)
  accepted <- list(); attempts_by <- c(S1 = 0L, S3 = 0L, S2 = 0L)
  total_target <- sum(s$per_scenario); done <- 0L
  for (sc in c("S1", "S3", "S2")) {
    target <- s$per_scenario[[sc]]; got <- 0L; attempt <- 0L
    while (got < target && attempt < s$max_attempt_factor * target) {
      attempt <- attempt + 1L
      p <- draw_dataset_params(sc, s, attempt)
      st <- run_scenario(p); gt <- ground_truth(st)
      if (!gt$converged || !gt$pluralistic_ignorance || gt$majority_share <= 0.5) next   # a strict majority that shows the pattern
      sv <- survey(st, s$respondents, survey_seed = p$seed + 500000L)
      if (!sample_shows_pattern(sv$respondents) || abs(mean(sv$respondents$attitude) - 0.5) < 1e-9) next   # the analysts must see the pattern too
      set.seed(p$seed + 700000L)
      flipped <- runif(1) < 0.5
      if (flipped) sv <- flip_coding(sv)
      sv <- anonymize_ids(sv, st$g$n)
      ee <- if ("ego_perceptions" %in% s$records) edge_end_estimates(sv$respondents, sv$ego_network)$net_misperception else NA_real_
      accepted[[length(accepted) + 1]] <- list(st = st, gt = gt, sv = sv, p = p, flipped = flipped, attempt = attempt, edge_end = ee)
      got <- got + 1L; done <- done + 1L
      if (!is.null(progress)) progress(done, total_target, sprintf("%s: %d of %d (attempt %d)", CLASS_NAMES[[scenario_label(p)]], got, target, attempt))
    }
    attempts_by[[sc]] <- attempt
  }
  if (length(accepted) == 0) stop("no dataset was accepted; increase the counts or widen the ranges")
  # blind the order
  set.seed(s$seed * 31L + 17L)
  ord <- sample.int(length(accepted))
  rows <- list()
  for (k in seq_along(ord)) {
    x <- accepted[[ord[k]]]; id <- sprintf("dataset_%04d", k)
    ddir <- file.path(out_dir, "blinded", "datasets", id); dir.create(ddir, recursive = TRUE, showWarnings = FALSE)
    ds <- apply_design(x$sv, s$records)
    write.csv(ds$respondents, file.path(ddir, "respondents.csv"), row.names = FALSE)
    if (!is.null(ds$ego_network)) write.csv(ds$ego_network, file.path(ddir, "ego_network.csv"), row.names = FALSE)
    if (s$write_state) saveRDS(list(attitude = x$st$a, declaration = x$st$D, conformity = x$st$conformity, edges = x$st$g$edges, params = x$st$params,
                                    respondents = x$sv$respondents, ego_network = x$sv$ego_network, coding_flipped = x$flipped),
                               file.path(out_dir, "key_details", paste0(id, ".rds")))
    p <- x$p; gt <- x$gt
    rows[[k]] <- data.frame(
      dataset_id = id, mechanism = MECHANISM[[p$scenario]], scenario = CLASS_NAMES[[scenario_label(p)]], scenario_code = scenario_label(p),
      n = p$n, respondents = x$sv$m, network = "preferential attachment", links_per_new_agent = p$m,
      prevalence_parameter = if (p$scenario == "S3") p$psi else p$pi0,
      conformity = if (p$scenario == "S2") "none (c = 0)" else sprintf("beta(%.2f, 1)", p$c_a),
      lambda = if (p$scenario == "S2") p$lambda else NA_real_, centrality = if (p$scenario == "S2") p$centrality else NA_character_,
      seed = p$seed, attempt = x$attempt, attitude_coding_flipped = x$flipped,
      majority_attitude_as_coded = if (x$flipped) 1L - gt$majority_attitude else gt$majority_attitude,
      majority_share = gt$majority_share, majority_mean_perceived_share = gt$majority_mean_perceived_share,
      pattern_in_sample = sample_shows_pattern(x$sv$respondents),
      # decomposition terms in the majority-attitude frame (pluralistic ignorance is the negative direction), independent of coding
      misperception_term = majority_frame(gt)$misperception, structure_term = majority_frame(gt)$structure,
      falsified_share = gt$falsified_share, deg_weighted_net_falsification = gt$deg_weighted_net_falsification,
      edge_end_test_in_sample_as_coded = x$edge_end, rounds = gt$rounds, stringsAsFactors = FALSE)
  }
  key <- do.call(rbind, rows)
  write.csv(key, file.path(out_dir, "key.csv"), row.names = FALSE)
  writeLines(blinded_readme(s$records, nrow(key)), file.path(out_dir, "blinded", "README.txt"))
  jsonlite::write_json(c(s, list(created = format(Sys.time(), "%Y-%m-%d %H:%M:%S"), attempts = as.list(attempts_by), accepted = as.list(table(key$scenario_code)))),
                       file.path(out_dir, "corpus.json"), auto_unbox = TRUE, pretty = TRUE)
  attr(key, "attempts") <- attempts_by
  key
}

# Score a predictions file against the key. predictions: data.frame with
# dataset_id, prediction ("genuine" / "structure", prefix match, case-insensitive),
# optional score = P(genuine).
score_predictions <- function(key, predictions) {
  pr <- predictions; names(pr) <- tolower(names(pr))
  stopifnot(all(c("dataset_id", "prediction") %in% names(pr)))
  pr$pred <- ifelse(grepl("^gen", tolower(trimws(pr$prediction))), "genuine pluralistic ignorance",
             ifelse(grepl("^(str|fri|net)", tolower(trimws(pr$prediction))), "friendship paradox", NA))
  m <- merge(key[, c("dataset_id", "mechanism", "scenario")], pr[, c("dataset_id", "pred", if ("score" %in% names(pr)) "score")], by = "dataset_id")
  ok <- !is.na(m$pred)
  acc <- mean(m$mechanism[ok] == m$pred[ok])
  conf <- table(truth = m$mechanism, predicted = m$pred, useNA = "ifany")
  by_sc <- tapply(m$mechanism == m$pred, m$scenario, mean, na.rm = TRUE)
  auc <- NA_real_
  if ("score" %in% names(m) && length(unique(m$mechanism)) == 2) {
    y <- m$mechanism == "genuine pluralistic ignorance"; sc <- as.numeric(m$score)
    r <- rank(sc); n1 <- sum(y); n0 <- sum(!y)
    auc <- (sum(r[y]) - n1 * (n1 + 1) / 2) / (n1 * n0)
  }
  list(n_scored = sum(ok), n_missing = nrow(key) - nrow(m), accuracy = acc, confusion = conf, accuracy_by_scenario = by_sc, auc = auc)
}

if (sys.nframe() == 0L && !interactive()) {
  args <- commandArgs(trailingOnly = TRUE)
  if (length(args) < 1) stop("usage: Rscript R/corpus.R <out_dir> [--per N] [--respondents M] [--seed S] [--no-state]")
  here <- dirname(normalizePath(sub("--file=", "", grep("--file=", commandArgs(), value = TRUE))))
  for (f in c("engine.R", "measure.R", "export.R")) source(file.path(here, f))
  s <- default_corpus_settings()
  if ("--per" %in% args) s$per_scenario[] <- as.integer(args[which(args == "--per") + 1])
  if ("--respondents" %in% args) s$respondents <- as.integer(args[which(args == "--respondents") + 1])
  if ("--seed" %in% args) s$seed <- as.integer(args[which(args == "--seed") + 1])
  if ("--no-state" %in% args) s$write_state <- FALSE
  key <- generate_blinded_corpus(s, args[1], progress = function(d, t, msg) if (d %% 10 == 0 || d == t) cat(sprintf("  %d / %d  %s\n", d, t, msg)))
  cat(sprintf("done: %d datasets in %s (attempts: %s)\n", nrow(key), args[1], paste(names(attr(key, "attempts")), attr(key, "attempts"), sep = "=", collapse = ", ")))
}
